kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  hostPath:
    path: /kubernetes/minio-data


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: minio-pv
  storageClassName: ""

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  hostPath:
    path: /kubernetes/mysql-data

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: mysql-pv
  storageClassName: ""

